#!/bin/sh
# -*- sh -*-
#
# Copyright (c) 2022 Yoshisato Yanagisawa
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer
#    in this position and unchanged.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

#%# family=auto
#%# capabilities=autoconf suggest

# Munin plugin for CPU temperature using pchtherm(4) on FreeBSD

export PATH=/sbin:/usr/bin:/bin

die() {
        echo "$@" 1>&2
        exit 1
}

cpus() {
        sysctl -N dev.pchtherm | awk -F. '$4 == "'"temperature"'" { print $3 }'
}

reqcpus() {
        cpus=$(cpus)
        if [ -z "$cpus" ] ; then
                die "No supported CPUs"
        fi
}

autoconf() {
	reqcpus
        if [ -n "$cpus" ] ; then
                echo "yes"
                exit 0
        else
                echo "no (function not supported by kernel)"
                exit 0
        fi
}

suggest() {
        if cpus >/dev/null ; then
            echo "temperature"
        fi
        exit $?
}

config() {
        reqcpus
        echo -n "graph_order"
        for cpu in $cpus ; do
                echo -n " CPU$cpu"
        done
        echo ""
        echo "graph_category sensors"
        echo "graph_scale no"
        echo "graph_title CPU Core Temperature"
        echo "graph_vlabel Core temperature in °C"
        for cpu in $cpus ; do
                echo "CPU$cpu.label CPU $cpu"
        done
        exit 0
}

get() {
        reqcpus
        for cpu in $cpus ; do
                echo -n "CPU$cpu.value "
                sysctl -n "dev.pchtherm.$cpu.temperature" | tr -d 'C'
        done
}

self=$(basename $0)

case "$*" in
autoconf)
        autoconf
        ;;
suggest)
        suggest
        ;;
config)
        config
        ;;
*)
        get
        ;;
esac

exit 0


